### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by Hermiten** [cybertiger/sql-converter#1]
Hi !

I have this error:

java.sql.SQLException: No suitable driver found for 127.0.0.1
        at java.sql.DriverManager.getConnection(DriverManager.java:596)
        at java.sql.DriverManager.getConnection(DriverManager.java:215)
        at org.cyberiantiger.minecraft.sqlconverter.Main.main(Main.java:301)

I check my pass, etc ... and all is good !

**Comment by cybertiger** [comment]
Your database URL was wrong.

This has to be the java specific database URL to access the database.

e.g. jdbc:mysql://localhost/pex
